- name: Install AArch64 Toolchain
  if: ${{ matrix.runner == 'ubuntu-22.04' }}
  run: sudo apt-get update && sudo apt-get install gcc-aarch64-linux-gnu libc6-dev-i386

- name: Install ARM Toolchain
  if: ${{ matrix.runner == 'ubuntu-22.04' }}
  run: sudo apt-get update && sudo apt-get install gcc-arm-linux-gnueabihf
