[env]
# We generally want to bypass updates in the build, they should only really be run in CI as they touch many parts of the host
PLOTINATOR_BYPASS_UPDATES = "true"

# Avoid linking with vcruntime140.dll by statically linking everything,
# and then explicitly linking with ucrtbase.dll dynamically.
# We do this, because vcruntime140.dll is an optional Windows component.
# NOTE: Endorsed by Microsoft devs: https://github.com/microsoft/edit/blob/d74c330f2b74134a7fd5f97f78933472049129d3/.cargo/release.toml
[target.'cfg(target_os = "windows")']
rustflags = [
    "-Ctarget-feature=+crt-static",
    "-Clink-args=/DEFAULTLIB:ucrt.lib",
    "-Clink-args=/NODEFAULTLIB:vcruntime.lib",
    "-Clink-args=/NODEFAULTLIB:msvcrt.lib",
    "-Clink-args=/NODEFAULTLIB:libucrt.lib",
]

# `web_sys_unstable_apis` is required to enable the web_sys clipboard API which egui_web uses.
# https://wasm-bindgen.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
# https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
#
# `getrandom_backend="wasm_js"` is required to enable the `getrandom` crate to use the `wasm_js` backend.
# https://docs.rs/getrandom/latest/getrandom/#webassembly-support
[target.wasm32-unknown-unknown]
rustflags = ['--cfg=web_sys_unstable_apis', '--cfg=getrandom_backend="wasm_js"']
