[env]
# We generally want to bypass updates in the build, they should only really be run in CI as they touch many parts of the host
PLOTINATOR_BYPASS_UPDATES = "true"

# Avoid linking with vcruntime140.dll by statically linking everything,
# and then explicitly linking with ucrtbase.dll dynamically.
# We do this, because vcruntime140.dll is an optional Windows component.
# NOTE: Endorsed by Microsoft devs: https://github.com/microsoft/edit/blob/d74c330f2b74134a7fd5f97f78933472049129d3/.cargo/release.toml
[target.'cfg(target_os = "windows")']
rustflags = [
    "-Ctarget-feature=+crt-static",
    "-Clink-args=/DEFAULTLIB:ucrt.lib",
    "-Clink-args=/NODEFAULTLIB:vcruntime.lib",
    "-Clink-args=/NODEFAULTLIB:msvcrt.lib",
    "-Clink-args=/NODEFAULTLIB:libucrt.lib",
]
