- name: Install Just
  uses: extractions/setup-just@v3
- name: Install HDF5
  shell: bash
  run: just init::install-hdf5-headers

- name: Run MSI installer (windows)
  if: runner.os == 'Windows'
  shell: pwsh
  run: |
    cd just\hdf
    msiexec /i HDF5-1.14.0-win64.msi /quiet /qn /norestart

# Need to overwrite it to fix: https://github.com/astral-sh/cargo-dist/pull/36
- name: Use patched cargo-dist version (windows)
  if: runner.os == 'Windows'
  run: cargo install cargo-dist \
          --git https://github.com/CramBL/cargo-dist \
          --branch fix-ignored-msvc-crt-static-flag \
          --rev a4cabb10395c7b275ea40d1636cd2d0e58be8af6